pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir('4-python-jenkins-docker-app') {
                    sh 'python3 -m py_compile app.py'
                }
            }
        }
        stage('Test') {
            steps {
                dir('4-python-jenkins-docker-app') {
                    sh 'python3 -m unittest discover tests'
                }
            }
        }
        stage('Docker Build') {
            steps {
                dir('4-python-jenkins-docker-app') {
                    sh 'docker build -t python-app:$BUILD_ID .'
                }
            }
        }
        stage('Docker Run') {
            steps {
                dir('4-python-jenkins-docker-app') {
                    sh 'docker run --rm python-app:$BUILD_ID'
                }
            }
        } 
        stage('Docker Tag & Push') {
            steps {
                dir('4-python-jenkins-docker-app') {
                          withCredentials([usernameColonPassword(credentialsId: 'dockerhub', variable: 'Dockerhublogin'), usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'dockerhubpass', usernameVariable: 'dockerhubuser')]) {
                        sh '''
                            docker login -u $dockerhubuser -p $dockerhubpass
                            docker tag python-app:$BUILD_ID  jaffardocker1991/python-app:$BUILD_ID
                            docker push jaffardocker1991/python-app:$BUILD_ID
                            docker rmi jaffardocker1991/python-app:$BUILD_ID
                            docker rmi python-app:$BUILD_ID
                        '''
                    }
                }
            }
        }         
    }
    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
