pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir('3-java-jenkins-docker-app') {
                sh 'mvn clean package'
                } 
            }
        }
        stage('Test') {
            steps {
                dir('3-java-jenkins-docker-app') {
                sh 'mvn test'
                }
            }
        }
        stage('Docker Build') {
            steps {
                dir('3-java-jenkins-docker-app') {
                sh 'docker build -t java-jenkins-docker:${BUILD_ID} .'
                }
            }
        }
        stage('Docker Run') {
            steps {
                dir('3-java-jenkins-docker-app') {
                sh 'docker run --rm java-jenkins-docker:${BUILD_ID}'
                }
            }
        }
        stage('Docker login') {
            steps {
               withCredentials([usernameColonPassword(credentialsId: 'dockerhub', variable: 'Dockerhublogin'), usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'dockerhubpass', usernameVariable: 'dockerhubuser')]) {
               sh 'docker login -u $dockerhubuser -p $dockerhubpass'
             } 
           }
        }  
        stage('Docker tag and push') {
            steps {
                sh "docker tag java-jenkins-docker:${BUILD_ID}  jaffardocker1991/java-jenkins-docker:${BUILD_ID}"
                sh "docker push jaffardocker1991/java-jenkins-docker:${BUILD_ID}"  
            }
        }
        stage('Docker clean after push') {
            steps {
                // Clean up the local copies so they don't waste disk space
                sh "docker rmi jaffardocker1991/java-jenkins-docker:${BUILD_ID}"
                sh "docker rmi java-jenkins-docker:${BUILD_ID}"
            }
        }
    }
    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
