pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir('3-java-jenkins-docker-app') {
                sh 'mvn clean package'
                } 
            }
        }
        stage('Test') {
            steps {
                dir('3-java-jenkins-docker-app') {
                sh 'mvn test'
                }
            }
        }
        stage('Docker Build') {
            steps {
                dir('3-java-jenkins-docker-app') {
                sh 'docker build -t java-jenkins-docker:latest .'
                }
            }
        }
        stage('Docker Run') {
            steps {
                dir('3-java-jenkins-docker-app') {
                sh 'docker run --rm java-jenkins-docker:latest'
                }
            }
        }
        stage('Docker login') {
            steps {
               withCredentials([usernameColonPassword(credentialsId: 'dockerhub', variable: 'Dockerhublogin'), usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'dockerhubpass', usernameVariable: 'dockerhubuser')]) {
               sh 'docker login -u $dockerhubuser -p $dockerhubpass'
             } 
           }
        }  
        stage('Docker tag and push') {
            steps {
                dir('3-java-jenkins-docker-app') {
                sh "docker tag java-jenkins  jaffardocker1991/java-jenkins-docker:${BUILD_ID}"
                sh "docker push jaffardocker1991/java-jenkins-docker:${BUILD_ID}"
                }
            }
        }
        
    }
}
